dist: xenial
language: python
stages:
  - name: "Lint and Test"
    if: branch = main AND (type = pull_request OR type = push)
jobs:
  include:
    - stage: "Lint and Test"
      name: "using python 3.6 "
      python: 3.6
    - name: "using python 3.7 "
      python: 3.7
    - name: "using python 3.8 "
      python: 3.8

before_install:
  - pip3 install poetry
  - poetry config virtualenvs.create false
install:
  - poetry install
script:
  - make lint
  - make test
  - poetry build
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "XtIo3VhakQG8yoCPcAsidncMGow27mmngGMy6PvHghojEO1gXUTvSe4Ub4UCbNUXpi3Xlo0AnI3YOu/FcfZpXxo08C/NtZq4+/xh8HeAWY9oJ2F3nyg0kYE3zApk1v3GKeBrD6lQnPYsfvRJT2M819skZcqZBMpMFBaRoPcJ+1KI52T0LIcG4tBWZCg5hys9isw8NFyyWwiqK1SJcVSJLcDOTSLCDbTKaGom5uT7niBnIdS5GqsjoXLTULPKzSiGK2V21yUqsYFLZoWOwc+u5aDl58lhSTsTOTkZvWXBtKvUPUMgVVjNzCVXNZJvr6c62FzBdfUK4aZzRxazoSs3WeiRgrShIpJO0odfCkbdRLj4FzSXmNw3+2AOLAmqMtnsrGVIEuJiNSwZIR6jcfJJ/V0HPMVPJCAXpPosxo6/MicjJsV4Kg+ARHKhS9dQ6DN1L9aysVW60uD4Mifdo4qPCj4Ihwmv1p48bQaicUOfQNYNPGi8l7tI9KMNgOBR/7Pl+hJQVNQ36G4Fw1Mj5B0vVQWzi8D8KBLCj52pT8HBTGpSO1ia6geQeP0IjSVpbgWkXDuVHnnuM+5w1mUeYyJk/ypy52r8VHBBqLuqtgMS8srkZzNTu6Jfz4IsR43Wig8l6/io2zGCLbPacaFKSH8wlzOtNeybvT2aG3Pvf6aKuE4="
  on:
    tags: true