dist: xenial
language: python

before_install:
  - pip3 install poetry
  - poetry config virtualenvs.create false
install:
  - poetry install

stages:
  - name: "lint and test"
    if: branch = main AND (type = push OR type = pull_request)
  - name: "build and publish"
    if: tag IS present
jobs:
  include:
    - stage: "lint and test"
      name: "lint using python 3.6 "
      python: 3.6
      script:
        - make lint
    - name: "lint using python 3.7 "
      python: 3.7
      script:
        - make lint
    - name: "lint using python 3.8 "
      python: 3.8
      script:
        - make lint
    - name: "test using python 3.6 "
      python: 3.6
      script:
        - make test
    - name: "test using python 3.7 "
      python: 3.7
      script:
        - make test
    - name: "test using python 3.8 "
      python: 3.8
      script:
        - make test
    - stage: "build and publish"
      python:
        - 3.8
      script:
        - poetry build
      deploy:
        provider: pypi
        username: "__token__"
        password:
          secure: "Hun3B7ZYu6XxAc4vo3oQHbtaXHFmD/ULkBkL9dmtSItiGEm7yOECP8xXX6j2O5fYXCr15IrC+QA21+ozHVXKq9ZybVsIISvmEE9Va9RCqgTYEGqzisOZWIUmnRCzBwAbMM33dSHZucLDlvHDNip20g2DRrEm1mGAnLEzB83c2ryTqjF6m843GgjpM5n22fH3RWyBDB+cIoA6RLwul7BnoNdYPIZdWbKXGNZM5WDinpnemC59VfrDnqTHN2ajI6ewL8yhlsnD7T1sDIofCzzhtxaNzSe+hHCJkHGvTOTRH+KVV0TyJ21Gag/q3ZY49VQMpB7o8FVjEA4oQJNm+e3vGtaxtbivtSUGbclMuChaedgybuW+ffIklJxh/jEqyVxt1i67bNAkSFzosk4CtGwcLA8c9fvP1bUKyI6vPhM9yYOxFMn4KPWwwiKB4gndME28n5QbXIcdarrjonHm19NbN57zBzjj7Te6w3HK2rVwajAOk0aYnQ6YfoekiWiDRshZxxltO7EO/zk2tksWy3rs2e4iubzEXgbjLj4OjYxgmLc4MdD3YrWkDCILz97MLeMrEHQjxZfD6Ji75W/DbTl045idj/AhmojjS8fjAa/neyZEigZIKGFDXXqv2yZbZKjjv975GXRxFpdE+cHeRONisidzZOgCFOHs43LUKDguy74="
        on:
          tags: true
          branch: main
